Parameters:
  InstanceType:
    Type: string
    AllowedValues:
      - t2.micro
      - t2.medium
      - t2.small
    Default: t2.micro

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      InstanceType: !Ref InstanceType
      ImageId: ami-0a3c3a20c09d6f377
